web/dolphinProject/accountapp/urls.py
from django.urls import path
from . import views

app_name = 'accountapp'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
]

web/dolphinProject/dolphinProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accountapp/', include('accountapp.urls')),
    path('subapp/', include('subapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #url/media/파일명 점근을 가능하게 한다.

web/dolphinProject/mainapp/urls.py
from django.urls import path 
from . import views

app_name = 'mainapp'
urlpatterns = [
    path('', views.home, name='home'), #127.0.0.1:8000/ 
    path('search/', views.search, name='search'),
    path('realtime/', views.realtime, name='realtime'),
    path('upload/', views.upload, name='upload'),
]

web/dolphinProject/subapp/urls.py
from django.urls import path 
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'subapp'
urlpatterns = [
    path('about/', views.about, name='about'), #127.0.0.1:8000/subapp/about
    path('mypage/', views.mypage, name='mypage'),

    path('<int:MusicDB_id>/', views.detail, name='detail'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:music_pk>/comments/new/', views.comments_new, name='comments_new'),
    path('<int:music_pk>/comments/<int:pk>/delete/', views.comments_delete, name = 'comments_delete'),
    path('<int:music_pk>/comments/<int:pk>/edit/', views.comments_edit, name ='comments_edit'),
    path('downloads', views.downloads, name='downloads'),
    path('profile/<username>/', views.profile, name='profile'),
    path('test/', views.test, name='test'), #127.0.0.1:8000/subapp/test
    path('<username>/follow/', views.follow, name='follow'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/dolphinProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ai dolphin - 세상의 모든 음향</title>
    <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">
    {% block style %}
    <!-- 각 html 파일별 추가 파일 들어가는 부분 -->
    {% endblock %}
</head>
<body>
    <div id='nav'>
        <div id='container'>
            <a href="{% url 'mainapp:home' %}">
                <img class='logo' src="{% static 'image/logo_text.png' %}" alt='ai dolphin logo'>
            </a>
            <div class="nav_search">
                <form action="{% url 'mainapp:search' %}" method="GET">
                    {% csrf_token %}
                    <input type="text" class="search-input" placeholder="search..." name="kw">
                    <button type="submit" class="search-icon">
                        AI
                        {% comment %} <img src="{% static 'image/white_search@0.5x.png' %}" alt='search icon'> {% endcomment %}
                    </button>
                </form>
            </div>
            <ul>
                <li><a href="{% url 'mainapp:home' %}">Home</a></li>
                <li><a href="{% url 'subapp:about' %}">About</a></li>
                <li><a href="{% url 'mainapp:search' %}">Search</a></li>
                <li><a href="{% url 'subapp:about' %}">Features</a></li>
                {% comment %} <li><a href="{% url 'subapp:about' %}">FAQ</a></li>                 {% endcomment %}
                {% if user.is_authenticated %}
                <!-- 로그인 한 사용자 -->
                    <li><a href="/subapp/profile/{{request.user.username}}">My Page</a></li>
                    <li><a href="{% url 'mainapp:upload' %}">Upload</a></li>
                    <li>
                        <form action="{% url 'accountapp:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="path" value="{{request.path}}">
                            <button id='logout' type = submit>Log-Out</button>
                        </form>
                    </li>
                {% else %}
                    <!-- 로그인하지 않은 사용자 -->
                     <!-- <li><a href="{% url 'accountapp:login' %}">Log-In</a></li> -->
                    <li><a href="{% url 'accountapp:login' %}?next={{ request.path }}">Log-in</a></li>
                    <li id='signup'><a href="{% url 'accountapp:sign_up' %}">Sign - up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% block content %}
    <!-- 여기에 각 html별 body내용 들어가는 부분 -->
    {% endblock %}
    <div id='bottom'>
        Made with aloha dolphin in South Korea © 2020 ai dolphin. All rights reserved.
    </div>
</body>
</html>

web/dolphinProject/templates/basehome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ai dolphin - 세상의 모든 음향</title>
    <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">
    {% block style %}
    <!-- 각 html 파일별 추가 파일 들어가는 부분 -->
    {% endblock %}
</head>
<body>
    <div id='nav'>
        <div id='container'>
            <a href="{% url 'mainapp:home' %}">
                <img class='logo' src="{% static 'image/logo_text.png' %}" alt='ai dolphin logo'>
            </a>
            <ul>
                <li><a href="{% url 'mainapp:home' %}">ai-dolphin</a></li>
                <li><a href="{% url 'subapp:about' %}">About Us</a></li>
                
                {% if user.is_authenticated %}
                <!-- 로그인 한 사용자 -->
                    <li><a href="{% url 'subapp:profile' request.user.username %}">My Page</a></li>
                    <li>
                        <form action="{% url 'accountapp:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="path" value="{{request.path}}">
                            <button type = submit>Log-Out</button>
                        </form>
                    </li>
                    <li><a href="{% url 'mainapp:upload' %}">Upload</a></li>
                {% else %}
                    <!-- 로그인하지 않은 사용자 -->
                    <!-- <li><a href="{% url 'accountapp:login' %}">Log-In</a></li> -->
                    <li><a href="{% url 'accountapp:login' %}?next={{ request.path }}">Log-In</a></li>
                    <li><a href="{% url 'accountapp:sign_up' %}">Sign-Up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% block content %}
    <!-- 여기에 각 html별 body내용 들어가는 부분 -->
    {% endblock %}
    <div id='bottom'>
        Made with aloha dolphin in South Korea © 2020 ai dolphin. All rights reserved.
    </div>
</body>
</html>