web/dolphinProject/dolphinProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accountapp/', include('accountapp.urls')),
    path('subapp/', include('subapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #url/media/파일명 점근을 가능하게 한다.

web/dolphinProject/subapp/urls.py
from django.urls import path 
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'subapp'
urlpatterns = [
    path('about/', views.about, name='about'), #127.0.0.1:8000/subapp/about
    path('mypage/', views.mypage, name='mypage'),

    path('<int:MusicDB_id>/', views.detail, name='detail'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:music_pk>/comments/new/', views.comments_new, name='comments_new'),
    path('<int:music_pk>/comments/<int:pk>/delete/', views.comments_delete, name = 'comments_delete'),
    path('<int:music_pk>/comments/<int:pk>/edit/', views.comments_edit, name ='comments_edit'),
    path('downloads', views.downloads, name='downloads'),
    path('profile/<username>/', views.profile, name='profile'),
    path('test/', views.test, name='test'), #127.0.0.1:8000/subapp/test
    path('<username>/follow/', views.follow, name='follow'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/dolphinProject/subapp/models.py
from django.db import models

# Create your models here.

web/dolphinProject/subapp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from mainapp.models import MusicDB,Comment,Profile,User
from django.db.models import Q, Count
from mainapp.forms import CommentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import math
# Create your views here.

def about(request):
    return render(request, 'subapp/about.html')

def detail(request,MusicDB_id):
    music= get_object_or_404(MusicDB, pk=MusicDB_id)
    comment_form = CommentForm()
    comments = music.comments.all()
    #comments=Comment.objects.all()
    user=get_object_or_404(User, username=music.author)
    profile = get_object_or_404(Profile, user=music.author)
    context = {
        'music':music,
        'comment_form': comment_form,
        'comments':comments,
        'profile':profile,
        'user':user,
    }
    return render(request,'subapp/detail.html',context)

@login_required(login_url='/accountapp/login')
def like(request,pk):
    musicdb = get_object_or_404(MusicDB, pk=pk)
    
    if request.user in musicdb.like.all():
            #좋아요 취소
        musicdb.like.remove(request.user)
    else:
        musicdb.like.add(request.user)
        
    return redirect('subapp:detail', musicdb.pk)

@login_required(login_url='/accountapp/login')
def comments_new(request, music_pk): #POST 
    # 1. 요청이 POST 인지 점검
    if request.method  == 'POST': 
        # 2. form에 data를 집어넣기 (목적 == 유효성 검사)
        form = CommentForm(request.POST)
        # request.POST #=>
        # 3. form에서 유효성 검사를 시행
        if form.is_valid():
            # 4. 통과하면 database에 저장 
            comment = form.save(commit=False)
            # 4-1. article 정보 주입
            comment.music_id = music_pk
            comment.author = request.user 
            comment.save()
    # 5. 생성된 댓글을 확인할 수 있는 곳으로 안내 
    return redirect('subapp:detail', music_pk)

@login_required(login_url='/accountapp/login')
def comments_delete(request, music_pk, pk): # POST 
    # 0. 요청이 POST인지 점검 
    if request.method == 'POST':
        # 1. pk를 가지고 삭제하려는 data를 꺼내오기 
        comment = Comment.objects.get(pk=pk)
        # 2. 삭제
        comment.delete()
    # 3. 삭제되었는지 확인 가능한 곳으로 안내 
    
    return redirect('subapp:detail', music_pk)
    
@login_required(login_url='/accountapp/login')
def comments_edit(request,music_pk, pk): # GET , POST 
    # Database에서 수정하려 하는 data 가져오기 
    comment = Comment.objects.get(pk=pk)

    # 수정권한 확인
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('subapp:detail', music_pk)

    # 0. 요청의 종류가 POST인지 GET인지 점검 
    if request.method == 'POST':
        # 실제로 수정 ! 
        # 1. form에 '넘어온 data' & '수정하려는 data' 집어넣기 
        form = CommentForm(request.POST, instance=comment)
        # 2. 유효성 검사 
        if form.is_valid():
            # 3. 검사를 통과했다면, save 
            comment = form.save()
            # 4. 변경된 결과 확인하는 곳으로 안내 
            return redirect('subapp:detail', music_pk)
    else : 
        # 수정 양식 보여주기! 
        # 1. form class 초기화 (생성)
        form = CommentForm(instance=comment)

    context ={
        'form' : form,
    }
    return render(request,'subapp/comments_edit.html', context)

def downloads(request):
    if request.method=='POST':
        pk = request.POST.get('music_id')
        music = MusicDB.objects.get(pk=pk)
        temp = music.downloads
        music.downloads = temp + 1
        music.save()

    return redirect('subapp:detail', pk)

def mypage(request):
    return render(request, 'subapp/mypage.html')
    
def test(request):
    # app별로 html파일이 있기때문에 " 앱이름/~.html " 로 경로지정해야함!
    return render(request, 'subapp/test.html')

# @login_required
def profile(request, username):
    context={}
    # 옵션값 가져오기
    sort = request.GET.get('sort', 'recent')
    context['sort'] = sort
    page = int(request.GET.get('page', 1))
    context['page'] = page
    paginated_by = 20
    #객체들 가져오기
    user = get_object_or_404(User, username=username)
    context['user'] = user
    profile = get_object_or_404(Profile, user=user)
    context['profile'] = profile
    musicdb = MusicDB.objects.filter(author=user)
    follow = profile.follow.all()
    context['follows'] = follow
    #뮤직DB정렬
    if sort == "like":
        musicdb = musicdb.annotate(num_like=Count('like')).order_by('-num_like','-date')
    elif sort == "downloads":
        musicdb = musicdb.order_by('-downloads', '-date')
    else : #recent:
        musicdb = musicdb.order_by('-date')
    #페이징
    start_idx = paginated_by * (page-1)
    end_idx = paginated_by * page
    total_count = musicdb.count()

    musicdb = musicdb[start_idx:end_idx]
    context['musicdb'] = musicdb

    total_page = math.ceil( total_count / paginated_by) 
    if page == 1 or page==2 or page==3: #첫페이지일때
        page_range = range(2, 7)
    elif page == total_page or page == total_page -1 or page == total_page -2 : #마지막 페이지 일때
        page_range = range(total_page-5, total_page)
    else:
        page_range = range(page-2, page+3)
    
    context['totalpage'] = total_page
    context['page_range'] = page_range

    return render(request,'subapp/profile.html', context)

@login_required(login_url='/accountapp/login')
def follow(request, username):
    if request.method == 'POST':
        try:
            user = get_object_or_404(User, username=username)
            profile = get_object_or_404(Profile, user=user)

            if request.user in profile.follow.all():
                profile.follow.remove(request.user)
            else:
                profile.follow.add(request.user)

            return redirect('subapp:profile', username)
        
        except Profile.DoesNotExist:
            pass

    return redirect('mainapp:home')

web/dolphinProject/subapp/templates/subapp/about.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <!-- 추가할내용이 있을경우(없으면 빈칸) -->
    <link rel="stylesheet" href="{% static 'subapp/about.css' %}"> 
{% endblock %}

{% block content %}
    <img id='info_img' src="{% static 'subapp/image/info.gif' %}" alt='info image'>
    <div id='title'>
        <h1>about ai dolphin</h1>
    </div>
    <div id='info'>
        <h1>ai dolphin</h1>
        <h3>이제 ai dolphin으로 필요한 음향을 쉽게 찾거나, 제작한 음향을 소비자에게 공급하세요!<h3>
    </div>
    <div id='info'>
        <h1>ai dolphin search</h1>
        <h3>원하는 데이터를 쉽고 빠르게 녹음, 업로드 하여 검색!<h3>
    </div>
    <div id='info'>
        <h1>저작권 기반 필터링</h1>
        <h3>사용 목적에 맞는 라이센스의 음향을 편리하게 사용하세요!<h3>
    </div>
    <div id='info'>
        <h1>ai dolphin 추천서비스</h1>
        <h3>AI classification, similarity 모델을 통한 유사 음향 추천<h3>
    </div>
    <div id='info'>
        <h1>ai dolphin 회원 서비스</h1>
        <h3>즐겨찾는 업로더, 음향 등을 관리하세요! 혹은 나의 페이지에 음향을 올리고 관리하세요<h3>
    </div>
{% endblock %}

web/dolphinProject/subapp/templates/subapp/comments_edit.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mainapp/search.css' %}"> 
{% endblock %}

{% block content %}
<div id='main_ct'>
    <h1> Comments Edit </h1>
    <form action="" method ="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="댓글수정">
    </form>
</div>
{% endblock %}

web/dolphinProject/subapp/templates/subapp/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'subapp/detail.css' %}" type='text/css'> 
{% endblock %}

<!-- body 부분에 들어갈 내용 -->
{% block content %}
    <div id='main_ct'>
        <div id='detail_left'>
            <div>
            {% if messages %}
                {% for message in messages %}
                <!--잘못된 수정 접근시 에러알림 거의 나올일이 없을 것 같다.-->
                {{message.tags}} : {{message.message}}
                {% endfor %}
            {% endif %}
            </div>
            <div id='file_name'>{{music.fname}}</div>
            <audio src='../../../media/music_sample/{{music.fname}}#t=,10' controls controlsList="nodownload">해당 브라우저는 오디오태그를 지원하지 않습니다.</audio>
            <form id='download' action="{% url 'subapp:downloads' %}" method="POST" id='downloads'>
                {% csrf_token %}
                <!--script는 맨 아래로 이동-->
                <a id='download_bt' href="../../../media/music_sample/{{music.fname}}" download onclick="return showConfirm();">Download</a>
                <!--<a href="../../../media/music_sample/{{music.fname}}" download onclick="document.getElementById('downloads').submit();">다운로드</a>-->
                <input type="hidden" name="music_id" value={{music.pk}}>
            </form>
            <br>
            <div>
                <img id='wave_img' src="../../../media/wave_image/{{music.fname}}.png" alt="파형이미지">
            </div>
            <!--music info-->
            <div>
                fname: {{music.fname}} <br>
                author:{% if music.author %}{{music.real_author}}{% else %}unknown{% endif %} <br> <!--마이페이지(업로더페이지)링크 달기-->
                label: {{music.label}} <br>
                mood : {{music.mood}}<br>
                licenses: {{music.licenses}} <br>
                date: {{music.date}} <br>
                {% if user.is_authenticated %} 
                <!--사용자가 로그인한 상태에서만 좋아요 버튼이 보인다-->
                    {% if request.user in music.like.all %}
                        <a href="{% url 'subapp:like' music.pk %}">
                        {% csrf_token %}
                        <!--버튼 이름은 좋아요 그대로인데 색깔로 바뀌면 좋겠다ㅎㅎ-->
                            <button type="button">(좋아요)취소</button>  &nbsp;
                        </a>
                    {% else %}
                        <a href="{% url 'subapp:like' music.pk %}">
                        {% csrf_token %}
                            <button type="button">좋아요</button>  &nbsp;
                        </a>
                    {% endif %}
                {% else %}
                    좋아요: 
                {% endif %}
                {{ music.like.count }} 명이 좋아합니다. <br>
                즐겨찾기 <br>
                다운로드 downloads: {{music.downloads}} <br>
                공유하기
                <!-- SNS share buttons --> 

            </div>
            <!--라이센스 설명부분 위치 재조정하기--><br>
            <div>
                <div>
                    {% if music.licenses == "Attribution" %}
                        <h3>Attribution (저작자표시 : CC BY)</h3>
                        <span>저작자의 이름, 저작물의 제목, 출처 등 저작자에 관한 표시를 해주어야 합니다.</span><br>
                        <img src="http://www.cckorea.org/images/ccl/lic_by_g.gif" alt="아이콘(CC BY)">
                    {% elif music.licenses == "Attribution Noncommercial" %}
                        <h3>Attribution Noncommercial (저작자표시-비영리 : CC BY-NC)</h3>
                        <span>저작자를 밝히면 자유로운 이용이 가능하지만 영리목적으로 이용할 수 없습니다.</span><br>
                        <img src="http://www.cckorea.org/images/ccl/lic_by_nc_g.gif" alt="아이콘(CC BY-NC)">
                    {% elif music.licenses == "Attribution Derivative Works" %}
                        <h3>Attribution Derivative Works (저작자표시-변경금지 : CC BY-ND)</h3>
                        <span>저작자를 밝히면 자유로운 이용이 가능하지만, 변경 없이 그대로 이용해야 합니다.</span><br>
                        <img src="http://www.cckorea.org/images/ccl/lic_by_nd_g.gif" alt="아이콘(CC BY-ND)">
                    {% elif music.licenses == "Attribution Share-alike" %}
                        <h3>Attribution Share-alike (저작자표시-동일조건변경허락 : CC BY-SA)</h3>
                        <span>저작자를 밝히면 자유로운 이용이 가능하고 저작물의 변경도 가능하지만, 2차적 저작물에는 원 저작물에 적용된 것과 동일한 라이선스를 적용해야 합니다.</span><br>
                        <img src="http://www.cckorea.org/images/ccl/lic_by_sa_g.gif" alt="아이콘(CC BY-SA)">
                    {% elif music.licenses == "ttribution Noncommercial Share-alike" %}
                        <h3>Attribution Noncommercial Share-alike (저작자표시-비영리-동일조건변경허락 : CC BY-NC-SA)</h3>
                        <span>저작자를 밝히면 이용이 가능하며 저작물의 변경도 가능하지만, 영리목적으로 이용할 수 없고 2차적 저작물에는 원 저작물과 동일한 라이선스를 적용해야 합니다.</span><br>
                        <img src="http://www.cckorea.org/images/ccl/lic_by_nc_sa_g.gif" alt="아이콘(CC BY-NC-SA)">
                    {% elif music.licenses == "Attribution Noncommercial Derivative Works" %}
                        <h3>Attribution Noncommercial Derivative Works (저작자표시-비영리-변경금지 : CC BY-NC-ND)</h3>
                        <span>저작자를 밝히면 자유로운 이용이 가능하지만, 영리목적으로 이용할 수 없고 변경 없이 그대로 이용해야 합니다.</span><br>
                        <img src="http://www.cckorea.org/images/ccl/lic_by_nc_nd_g.gif" alt="아이콘(CC BY-NC-ND)">
                    {% elif music.licenses == "Creative Commons 0" %}
                        <h3>Creative Commons 0 (저작권없음 : CC0)</h3>
                        <span>영리적인 목적을 포함한 어떤 목적으로든 그리고 어떤 방법으로든 그 저작물을 사용할 수 있습니다.</span><br>
                        <img src="//upload.wikimedia.org/wikipedia/commons/thumb/6/69/CC0_button.svg/88px-CC0_button.svg.png" alt="아이콘(CC0)">
                    {% else %}
                        error
                    {% endif %}
                </div>
                <div id='ccl_info'>
                <h4>CCL (Creative Commonss License)<a id='ccl_link' href="http://ccl.cckorea.org/about/"> 설명 바로가기</a></h4>
                <p>CCL은 자신의 창작물에 대하여 일정한 조건 하에 다른 사람이 자유로운 이용을 허락하는 내용의 자유이용 라이선스(License)입니다.</p>
                </div>
                <div style="width: 100%; text-align: center;"> 
                    <!-- Facebook share button --> 
                    <a href="" onclick="window.open(url_combine_fb, '', 'scrollbars=no, width=600, height=600'); return false;">
                    <img src="https://imgur.com/2pxqHxt.png" title="페이스북으로 공유하기" class="sharebtn_custom" style="width: 48px;"></a> 
                    <!-- Twitter share button --> 
                    <a href="" onclick="window.open(url_combine_tw, '', 'scrollbars=no, width=600, height=600'); return false;">
                    <img src="https://imgur.com/z7V4qga.png" title="트위터로 공유하기" class="sharebtn_custom" style="width: 48px;"></a> 
                    <!-- Naver share button --> 
                    <a href="" onclick="window.open(url_combine_naver, '', 'scrollbars=no, width=600, height=600'); return false;">
                    <img src="https://imgur.com/AYqtESo.png" title="네이버로 공유하기" class="sharebtn_custom" style="width: 48px;"></a> 
                    <!-- Kakao story share button --> 
                    <a href="" onclick="window.open(url_combine_ks, '', 'scrollbars=no, width=600, height=600'); return false;">
                    <img src="https://imgur.com/mIW39pd.jpg" title="카카오스토리로 공유하기" class="sharebtn_custom" style="width: 48px;"></a>
                </div>
            </div>
        </div> <!--container end-->
        <div id='detail_right'>
            {% comment %} <img src="{% static 'subapp/image/user_bg.svg' %}"> {% endcomment %}
            <div id='uploader'>
                <h2>Uploader</h2>
                <!--<img src="{% static 'image/userprofile.png' %}">-->
                <!--업로더 이미지-->
                {% if user.profile.image %}
                <img src="{{ MEDIA_URL }}{{ user.profile.image.url }}" alt="{{ user.username }}" style="width:200px; margin-left:25px;">
                {% else %}
                <img src="{% static 'default.png' %}" alt="{{ user.username }}">
                {% endif %}
                <h2>{% if music.author %}<a href="/subapp/profile/{{music.author}}">{{music.author}}</a>{% else %}unknown{% endif %} </h2>
                <!--업로더 소개글-->
                {% if user.profile.about_me %}
                <p class="card-text">소개글: {{ user.profile.about_me }}</p>
                {% else %}
                <p>소개글: 소개글을 작성해주세요</p>
                {% endif %}
                Member joined: {{user.date_joined | date:'Y.m.d'}}
            </div>
        </div>
    </div>
    <div id='main_ct'>
        <div>
            <a href="javascript:history.back()">목록(뒤로가기)</a>

            <!-- 댓글 입력창 -->
            <h3>댓글 입력</h3>
            {% if user.is_authenticated %}
            <form action="{% url 'subapp:comments_new' music.pk%}" method="POST">
                {% csrf_token %}
                {{ comment_form }}
                <input type ="submit" value="댓글작성">
            </form>
            {% else %}
                로그인 후 댓글 작성이 가능합니다.
            {% endif %}

            <!-- 댓글 목록 -->
            <h3>댓글 목록 ({{ comments|length }})</h3>

            <!-- +length, .count 갯수 구하기-->
            <table >
                <tr>
                    <th>작성자</th>
                    <th>댓글</th>
                    <th>날짜</th>
                    <th></th>
                </tr>
                {% for comment in comments %}
                <tr>
                    <td>{% if comment.author %}{{ comment.author }}{% else %}알수없음{% endif %}</td>
                    <td>{{ comment.text }}</td>
                    <td>{{ comment.date }}</td>
                    <td>
                        {% if user.is_authenticated and comment.author.pk == request.user.pk %}
                        <a href="{% url 'subapp:comments_edit' music.pk comment.pk %}">Edit</a>
                        <form action="{% url 'subapp:comments_delete' music.pk comment.pk %}" method = "POST">
                            {% csrf_token %}
                            <input type="submit" value="Delete!" onclick="return confirm('댓글을 삭제하시겠습니까?');">
                        </form>
                        {% endif %}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    작성된 댓글이 없습니다 :(
                </tr>
                {% endfor %}
            </table>
            <br>
        </div>
        <!-- SNS share websites --> 
        <script type="text/javascript" async> 
            var url_default_ks = "https://story.kakao.com/share?url=";
            var url_default_fb = "https://www.facebook.com/sharer/sharer.php?u=";
            var url_default_tw_txt = "https://twitter.com/intent/tweet?text="; 
            var url_default_tw_url = "&url="; 
            var url_default_naver = "http://share.naver.com/web/shareView.nhn?url="; 
            var title_default_naver = "&title="; 
            var url_this_page = location.href; 
            var title_this_page = document.title; 
            var url_combine_ks = url_default_ks + url_this_page; 
            var url_combine_fb = url_default_fb + url_this_page; 
            var url_combine_tw = url_default_tw_txt + document.title + url_default_tw_url + url_this_page; 
            var url_combine_naver = url_default_naver + encodeURI(url_this_page) + title_default_naver + encodeURI(title_this_page); 


            function showConfirm() {
                    if (confirm("저작물 이용에 관한 사항을 확인하셨습니까?(동의/반대)"))
                    {                                                                              
                        alert("파일을 다운로드 합니다.");
                        document.getElementById('downloads').submit();

                        return true;
                    } else {
                        alert("다운로드 하려면 확인 사항을 읽고 확인 버튼을 누르세요.");
                        return false;
                    }
                }
        </script>
    </div>
{% endblock %}

web/dolphinProject/subapp/templates/subapp/profile.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'subapp/profile.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}

<!-- body 부분에 들어갈 내용 -->
{% block content %}
    <div id='main_ct'>
        <h1>My Page</h1>
        <!--프로필 이미지-->
        <div>
            {% if user.profile.image %}
            <img id='profile_img' src="{{ MEDIA_URL }}{{ user.profile.image.url }}" alt="{{ user.username }}">
            {% else %}
            <img id='profile_img' src="{% static 'default.png' %}" alt="{{ user.username }}">
            {% endif %}
        </div>
        <!--이름 및 자기소개-->
        <div class="card-body col-9">
            <div id='user_name' class="card-title my-3">{{ user.username }}</div>
            {% if user.profile.about_me %}
                <p class="card-text">{{ user.profile.about_me }}</p>
            {% else %}
                <p>소개글을 작성해주세요</p>
            {% endif %}
        </div>
        <div id='user_data'>
            ________________________________________________<br>
            내가 업로드한 음향: 
            <!--정렬 기준 선택-->
            <div>
                <form action="{% url 'subapp:profile' user.username %}" method="GET">
                    {% csrf_token %}
                    <input type="radio" name="sort" value="recent" id="recent"{% if sort == 'recent' %}checked{%endif%}><label for="recent">최신순</label>
                    <input type="radio" name="sort" value="downloads" id="downloads" {% if sort == 'downloads' %}checked{%endif%} ><label for="downloads">다운로드순</label>
                    <input type="radio" name="sort" value="like" id="like" {% if sort == 'like' %}checked{%endif%} ><label for="like">좋아요순</label>
                    <button id='sort_bt' type="submit">적용</button>
                </form>
            </div>
            <!--정렬 결과-->
            <table id='user_table'>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Lable</th>
                        <th>License</th>
                        <th>Like</th>
                        <th>Download</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                {% for music in musicdb %}
                    <tr>
                        <td><a href="/subapp/{{music.pk}}">{{ music.fname }}</a></td>
                        <td>{{ music.label }}</td>
                        <td>{{ music.licenses }}</td>
                        <td>{{ music.like.count }}</td>
                        <td>{{ music.downloads }}</td>
                        <td>{{ music.date }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <ul id='paging'>
            <!--1페이지 고정-->
                {% if page == 1 %}
                <li><a href="{% url "subapp:profile" user.username %}?page=1"><b>처음</b></a></li>
                {% else %}
                <li><a href="{% url "subapp:profile" user.username %}?page=1">처음</a></li>
                {% endif %}
            <!--중간 앞 뒤 5개-->
                {% for pager in page_range %}
                    {% if pager == page %}
                    <li><a href="{% url "subapp:profile" user.username %}?page={{pager}}"><b>{{pager}}</b></a></li>
                    {%else%}
                    <li><a href="{% url "subapp:profile" user.username %}?page={{pager}}">{{pager}}</a></li>
                    {%endif%}
                {% endfor %}
            <!--마지막 페이지 고정-->
              {%if page == totalpage %}
              <li><a href="{% url "subapp:profile" user.username %}?page={{totalpage}}"><b>마지막</b></a></li>
              {% else %}
              <li><a href="{% url "subapp:profile" user.username %}?page={{totalpage}}">마지막</a></li>
              {% endif %}
            </ul>
            ________________________________________________
            <div>
                팔로워 :{{ user.profile.follow.count}} 명
                > <a onclick = "follwMore()" id="more">팔로워 목록 보기</a>
                <div id = "followList" style="display:none;" >
                    {%for follow in follows%}
                        <p>{{follow}}</p>
                    {%empty%}
                        <p>팔로워가 없습니다.</p>
                    {%endfor%}
                </div>
          <!--follow 버튼-->
          {% if request.user in follows.all %}
              <form action="{% url 'subapp:follow' user.username %}" method="POST">
                  {% csrf_token %}
                  <button id='follow_bt' type="submit">Unfollow</button>
              </form>
          {% else %}
              <form action="{% url 'subapp:follow' user.username %}" method="POST">
                  {% csrf_token %}
                  <button id='follow_bt' type="submit" user.username >Follow</button>
              </form>
          {% endif %}
        </div> 
        </div>
  </div>
  <img id='profile_bg' src={% static 'subapp/image/profile_bg.png' %}>
  <script>
    function follwMore(){
      if(followList.style.display=='none'){
          $('#followList').show();
          more.innerText='팔로워 목록 접기';
      }else{
          $('#followList').hide();
          more.innerText='팔로워 목록 보기';
      }
    }
  </script>
{% endblock %}

web/dolphinProject/subapp/templates/subapp/test.html
<!-- base 템플릿을 불러오는 부분 -->
{% extends 'base.html' %}
{% load static %}

<!-- head 부분 추가로 들어갈 내용 -->
{% block style %}
    <!-- 추가할내용(css, javascript, ... )이 있을 경우 여기에 추가(없으면 빈칸) -->
    <link rel="stylesheet" href="{% static 'subapp/test.css' %}"> 
{% endblock %}

<!-- body 부분에 들어갈 내용 -->
{% block content %}
    <h1>테스트 페이지</h1>
    <div>
        accountapp: 로그인 관련기능 <br>
        ㄴlogin.html <br><br>

        mainapp : 검색기능(주기능)/ 나중에 DB들어갈 app(아마도...) <br>
        ㄴhome.html search.html <br><br>

        subapp : 추가 기능 <br>
        ㄴ about.html, detail.html <br>
        ㄴ test(예시/테스트 파일) <br><br>

        * 각 앱별 urls.py에서 urlpattern 정의 ( dolphinProject > urls.py (x) ) <br>
        * templates, static 폴더에서 파일 불러올때 앱이름/파일 형태로 가져오기 <br><br>
    </div>
    <div>
        이미지 파일 불러오기 예시 <br>
        1. root 디렉토리 static>image>파일 <br>
        <img src="{% static 'image/search@0.5x.png' %}" alt="전체이미지예시"> <br>
        2. 앱 > static> image>파일 <br>
        <img src="{% static 'subapp/image/sample.png' %}" alt="앱이미지예시"><br>
    </div>
    
{% endblock %}